language: perl6
perl6:
  - latest
install:
  - rakudobrew build-panda
  - panda --notests installdeps .
  - panda --notests install git://github.com/tokuhirom/p6-Raw-Socket.git
script:
  - perl6 -MPanda::Builder -e 'Panda::Builder.new.build($*CWD)'
  - PERL6LIB=$PWD/lib prove -e perl6 -r t/
sudo: false
